# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
# import agf_mc_protocol
# from agf_mc_protocol import agf_mc_protocol as plc
from datetime import time
from enum import Enum
import time as ori_time
from datetime import *
import logging
from PyQt5.QtCore import QTime
import pymcprotocol
import traceback
pymc3e = pymcprotocol.Type3E(plctype="L")
# GLOBAL VARIABLE
connected_plc = False
# plc = agf_mc_protocol
cur_floor = 1
target_floor = 1
pre_counter = 0
cur_counter = 0
pause = False
error = None
# INPUT PLC
carry_in_request = [1030,1031,1032]
carry_in_completed = [1040,1041,1042]
carry_out_request = [1050,1051,1052]
carry_out_completion = [1060,1061,1062]
destination_ST_indication = [100,102,104]
carry_in_ID = [120,121,122]
request_door_open = [1090,1091,1092]
id_floor_destination = [1001,1002,1003]

# OUTPUT PLC
carry_in_instruction_possible = [2020,2021,2022]
carry_in_possible = [2050,2051,2052]
loading_and_unloading = [2060,2061,2062]
carrying_out_possible = [2070,2071,2072]
completion_ACK = [2080,2081,2082]
carry_out_ID = [30,31,32]

x_value_address = [1000,1001,1002,1003,1030,1031,1032,1040,1041,1042,1050,1051,1052,1060,1061,1062,1090,1091,1092]
y_value_address = [2004,2020,2021,2022,2050,2051,2052,2060,2061,2062,2070,2071,2072,2080,2081,2082,1062,1090,1091,1092]
w_value_address_input = [100,102,104,120,121,122]
w_value_address_output = [15,30,31,32]

pre_x_value = []
pre_y_value = []
pre_w_value_input = []
pre_w_value_output = []


def check_plc_connected():
    try:
        if pymc3e._is_connected:
            return True
        else:
            return False
    except:
        raise
def plc_connect(plc_address, port):
    """Connect to PLC

    Args:
        ip (str):       ip address(IPV4) to connect PLC
        port (int):     port number of connect PLC

    """
    try:
        pymc3e.connect(ip=plc_address, port=port)
        return True
    except:
        raise


def read_x(device, size=1):
    """Read input X

    Args:
        device(int):    Read head device. (ex: "X1")
        size(int):          Number of read device points. default size = 1

    Returns:
        values(list[int]):  bit units value(0 or 1) list

    """
    try:
        device = hex(int(str(device), base=8))
        return pymc3e.batchread_bitunits(headdevice='X'+ device, readsize=size)
    except:
        raise


def read_y(device, size=1):
    """Read output Y

    Args:
        device(int):    Read head device. (ex: "Y1")
        size(int):          Number of read device points. default size = 1

    Returns:
        values(list[int]):  bit units value(0 or 1) list

    """
    try:
        device = hex(int(str(device), base=8))
        return pymc3e.batchread_bitunits(headdevice='Y'+ device, readsize=size)
    except:
        raise


def read_m(register, size=1):
    """Read bit M

    Args:
        register(int):    Read head device. (ex: "M1")
        size(int):          Number of read device points. default size = 1

    Returns:
        values(list[int]):  bit units value(0 or 1) list

    """
    try:
        return pymc3e.batchread_bitunits(headdevice='M'+str(register), readsize=size)
    except:
        raise


def read_d(register, size=1):
    """Read in word register.

    Args:
        register(int):    Read head device. (ex: "D1000")
        readsize(int):      Number of read device points. default size = 1

    Returns:
        values(list[int]):  word units value list

    """
    try:
        return pymc3e.batchread_wordunits(headdevice='D'+str(register), readsize=size)
    except:
        raise

def read_w(register, size=1):
    """Read in word register.

    Args:
        register(int):    Read head device. (ex: "W1000")
        readsize(int):      Number of read device points. default size = 1

    Returns:
        values(list[int]):  word units value list

    """
    try:
        return pymc3e.batchread_wordunits(headdevice='W'+str(register), readsize=size)
    except:
        raise

def write_y(device, value):
    """Write output Y

    Args:
        device(int):    Write head device. (ex: "Y10")
        values(list[int]):  Write values. each value must be 0 or 1. 0 is OFF, 1 is ON.

    Returns:
        values(bool):  write success is true

    """
    try:
        device = hex(int(str(device), base=8))
        pymc3e.batchwrite_bitunits(headdevice='Y'+ device, values=value)
        return True
    except:
        raise


def write_m(register, value):
    """Write bit M

    Args:
        device(int):    Write head device. (ex: "M10")
        values(list[int]):  Write values. each value must be 0 or 1. 0 is OFF, 1 is ON.

    Returns:
        values(bool):  write success is true

    """
    try:
        pymc3e.batchwrite_bitunits(headdevice='M'+str(register), values=value)
        return True
    except:
        raise


def write_d(register, value):
    """Write register D

    Args:
        device(int):    Write head device. (ex: "D1000")
        values(list[int]):  Write values.

    Returns:
        values(bool):  write success is true

    """
    try:
        pymc3e.batchwrite_wordunits(headdevice='D'+str(register), values=value)
        return True
    except:
        raise

def write_w(register, value):
    """Write register D

    Args:
        device(int):    Write head device. (ex: "w1000")
        values(list[int]):  Write values.

    Returns:
        values(bool):  write success is true

    """
    try:
        pymc3e.batchwrite_wordunits(headdevice='W'+str(register), values=value)
        return True
    except:
        raise




class Color(Enum):
    RED = "rgba(255,0,0,255)"
    YELLOW = "rgba(255,255,0,255)"
    WHITE = "rgba(255,255,255,255)"
class MainStatePlace(Enum):
    NONE = -1
    CHECK_ELEVATOR_POSIBLE = 0
    REQUEST_ENTER_ELEVATOR = 1
    CHECK_ENTER_POSSIBLE = 2
    CHECK_AGV_PLACE_COMPLETE = 3
    DONE_CARRY_IN = 4
    PAUSE = 5

class MainStatePick(Enum):
    NONE = -1
    CHECK_ELEVATOR_POSIBLE = 0
    REQUEST_ENTER_ELEVATOR = 1
    CHECK_ENTER_POSSIBLE = 2
    CHECK_AGV_PICK_COMPLETE = 3
    DONE_CARRY_OUT = 4
    PAUSE = 5

class ThreadAuto(QtCore.QThread):
    signal = pyqtSignal(int)
    signal_dest = pyqtSignal(int)
    completed = pyqtSignal(bool)
    log = pyqtSignal(str)
    def __init__(self, index=0):
        super().__init__()
        self.index = index
    def reset(self):
        for i in x_value_address:
            write_m(i,[0])
        for i in w_value_address_input:
            write_w(i,[0])
    def read_value_x(self):
        global pre_x_value
        index = 0
        for i in x_value_address:
            if stop:
                break
            if index == 0:
                index += 1
                continue
            value = read_m(i,1)[0]
            if pre_x_value[index] != value:
                self.log.emit("Write data  X{} = {} to PLC".format(i, value ))
                pre_x_value[index] = value
            index += 1
    def read_value_y(self):
        global pre_y_value
        index = 0
        for i in y_value_address:
            if stop:
                break
            value = read_m(i,1)[0]
            if pre_y_value[index] != value:
                self.log.emit("Read data Y{} = {} from PLC".format(i, value ))
                pre_y_value[index] = value
            index += 1
    def read_value_w_input(self):
        global pre_w_value_input
        index = 0
        for i in w_value_address_input:
            if stop:
                break
            value = read_w(i,1)[0]
            if pre_w_value_input[index] != value:
                self.log.emit("Write data W{} = {} to PLC".format(i, value ))
                pre_w_value_input[index] = value
            index += 1
    def read_value_w_output(self):
        global pre_w_value_output
        index = 0
        for i in w_value_address_output:
            if stop:
                break
            value = read_w(i,1)[0]
            if pre_w_value_output[index] != value:
                self.log.emit("Read data W{} = {} from PLC".format(i, value ))
                pre_w_value_output[index] = value
            index += 1
    def reset_value_all(self):
        global pre_x_value, pre_y_value, pre_w_value_input, pre_w_value_output
        pre_x_value = []
        pre_y_value = []
        pre_w_value_input = []
        pre_w_value_output = []
        for i in range(len(x_value_address)):
            pre_x_value.append(0)
        for i in range(len(y_value_address)):
            pre_y_value.append(0)
        for i in range(len(w_value_address_input)):
            pre_w_value_input.append(0)
        for i in range(len(w_value_address_output)):
            pre_w_value_output.append(0)
    def run(self):
        global error
        print('Starting thread...', self.index)
        self.reset()
        self.reset_value_all()
        pose_agv_cur_floor = 1
        pose_agv_dest_floor = 1
        finish = False
        self.state = MainStatePlace.CHECK_ELEVATOR_POSIBLE
        self.pre_state = None
        self.state_when_pause = None
        t1 = datetime.now()
        begin_time_source = datetime.now()
        on_bit = True
        turn_off_when_carry_in_finish = False
        turn_off_when_carry_out_finish = False
        error = None
        if cur_floor == target_floor:
            error = "It is not possible to choose Current Floor with a value equal to Target Floor"
            finish = True
            self.completed.emit(finish)
            return
        self.log.emit("Mission started")
        while(True):
            self.read_value_x()
            self.read_value_y()
            self.read_value_w_input()
            self.read_value_w_output()
            if self.pre_state != self.state:
                print("{} -------> {}".format(self.pre_state, self.state))
                self.pre_state = self.state
            self.signal.emit(pose_agv_cur_floor)
            self.signal_dest.emit(pose_agv_dest_floor)
            self.completed.emit(finish)
            if not connected_plc:
                self.log.emit("Plc disconnected")
                self.stop()
            if (datetime.now() - t1).seconds >= 1:
                if on_bit:
                    write_m(1000,[1])
                    t1 = datetime.now()
                    on_bit = False
                else:
                    write_m(1000,[0])
                    t1 = datetime.now()
                    on_bit = True
            write_m(1001,[1])

            # CARRY_IN
            if self.state == MainStatePlace.CHECK_ELEVATOR_POSIBLE:
                pose_agv_cur_floor = 1
                if read_m(carry_in_instruction_possible[cur_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_cur_floor = 2
                        self.state = MainStatePlace.REQUEST_ENTER_ELEVATOR
                        begin_time_source = datetime.now()
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE

            elif self.state == MainStatePlace.REQUEST_ENTER_ELEVATOR:
                write_w(destination_ST_indication[cur_floor-1], [id_floor_destination[target_floor-1]])
                write_w(carry_in_ID[cur_floor-1], [1])
                write_m(carry_in_request[cur_floor-1], [1])
                write_m(request_door_open[cur_floor-1], [1])
                if read_m(carry_in_possible[cur_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_cur_floor = 3
                        begin_time_source = datetime.now()
                        self.state = MainStatePlace.CHECK_AGV_PLACE_COMPLETE
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePlace.CHECK_AGV_PLACE_COMPLETE:
                if (datetime.now() - begin_time_source).seconds >= 3:
                    write_m(carry_in_completed[cur_floor-1], [1])
                    pose_agv_cur_floor = 2
                    if read_w(15,1)[0] == 1 and read_m(2004,1)[0]:
                        self.state = MainStatePlace.DONE_CARRY_IN
                        turn_off_when_carry_in_finish = True
                        begin_time_source = datetime.now()
                        t = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePlace.DONE_CARRY_IN:
                if (datetime.now() - t).seconds >= 5:
                    pose_agv_cur_floor = 1
                    self.state = MainStatePick.CHECK_ELEVATOR_POSIBLE
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE

            # CARRY_IN
            elif self.state == MainStatePick.CHECK_ELEVATOR_POSIBLE:
                pose_agv_dest_floor = 1
                if read_w(carry_out_ID[target_floor-1],1)[0] == 1 and read_m(loading_and_unloading[target_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_dest_floor = 2
                        self.state = MainStatePick.REQUEST_ENTER_ELEVATOR
                        begin_time_source = datetime.now()
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE

            elif self.state == MainStatePick.REQUEST_ENTER_ELEVATOR:
                write_m(carry_out_request[target_floor-1], [1])
                if read_m(carrying_out_possible[target_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_dest_floor = 3
                        self.state = MainStatePick.CHECK_AGV_PICK_COMPLETE
                        begin_time_source = datetime.now()
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE

            elif self.state == MainStatePick.CHECK_AGV_PICK_COMPLETE:
                if (datetime.now() - begin_time_source).seconds >= 3:
                    write_m(carry_out_completion[target_floor-1], [1])
                    pose_agv_dest_floor = 2
                    if read_m(completion_ACK[target_floor-1], 1)[0]:
                        t = datetime.now()
                        self.state = MainStatePick.DONE_CARRY_OUT
                        turn_off_when_carry_out_finish = True
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePick.DONE_CARRY_OUT:
                if (datetime.now() - t).seconds >= 5:
                    pose_agv_dest_floor = 1
                    finish = True
                    self.completed.emit(finish)
                    self.signal_dest.emit(pose_agv_dest_floor)
                    self.log.emit("Mission finished")
                    break
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePlace.PAUSE:
                if read_m(1002,1)[0] == 0:
                    write_m(1002,[1])
                    self.log.emit("Agv error")
                if not pause:
                    self.log.emit("Agv normal")
                    if read_m(1002,1)[0] == 1:
                        write_m(1002,[0])
                    self.state = self.state_when_pause
            if turn_off_when_carry_in_finish:
                 if (datetime.now() - t).seconds >= 1:
                    turn_off_when_carry_in_finish = False
                    write_m(carry_in_completed[cur_floor-1], [0])
                    ori_time.sleep(0.5)
                    write_w(destination_ST_indication[cur_floor-1], [0])
                    write_w(carry_in_ID[cur_floor-1], [0])
                    write_m(carry_in_request[cur_floor-1], [0])
                    write_m(request_door_open[cur_floor-1], [0])
            if turn_off_when_carry_out_finish:
                 if (datetime.now() - t).seconds >= 1:
                    turn_off_when_carry_out_finish = False
                    write_m(carry_out_request[target_floor-1], [0])
                    write_m(carry_out_completion[target_floor-1], [0])
            ori_time.sleep(0.1)
    def stop(self):
        print('Stopping thread...', self.index)
        self.log.emit("Stop mission")
        self.terminate()

class ThreadManual(QtCore.QThread):
    signal = pyqtSignal(int)
    signal_dest = pyqtSignal(int)
    completed = pyqtSignal(bool)
    status = pyqtSignal(int)
    log = pyqtSignal(str)
    def __init__(self, index=0):
        super().__init__()
        self.index = index
    def reset(self):
        for i in x_value_address:
            write_m(i,[0])
        for i in w_value_address_input:
            write_w(i,[0])
    def read_value_x(self):
        global pre_x_value
        index = 0
        for i in x_value_address:
            if stop:
                break
            if index == 0:
                index += 1
                continue
            value = read_m(i,1)[0]
            if pre_x_value[index] != value:
                self.log.emit("Write data  X{} = {} to PLC".format(i, value ))
                pre_x_value[index] = value
            index += 1
    def read_value_y(self):
        global pre_y_value
        index = 0
        for i in y_value_address:
            if stop:
                break
            value = read_m(i,1)[0]
            if pre_y_value[index] != value:
                self.log.emit("Read data Y{} = {} from PLC".format(i, value ))
                pre_y_value[index] = value
            index += 1
    def read_value_w_input(self):
        global pre_w_value_input
        index = 0
        for i in w_value_address_input:
            if stop:
                break
            value = read_w(i,1)[0]
            if pre_w_value_input[index] != value:
                self.log.emit("Write data W{} = {} to PLC".format(i, value ))
                pre_w_value_input[index] = value
            index += 1
    def read_value_w_output(self):
        global pre_w_value_output
        index = 0
        for i in w_value_address_output:
            if stop:
                break
            value = read_w(i,1)[0]
            if pre_w_value_output[index] != value:
                self.log.emit("Read data W{} = {} from PLC".format(i, value ))
                pre_w_value_output[index] = value
            index += 1
    def reset_value_all(self):
        global pre_x_value, pre_y_value, pre_w_value_input, pre_w_value_output
        pre_x_value = []
        pre_y_value = []
        pre_w_value_input = []
        pre_w_value_output = []
        for i in range(len(x_value_address)):
            pre_x_value.append(0)
        for i in range(len(y_value_address)):
            pre_y_value.append(0)
        for i in range(len(w_value_address_input)):
            pre_w_value_input.append(0)
        for i in range(len(w_value_address_output)):
            pre_w_value_output.append(0)
    def run(self):
        global error
        print('Starting thread...', self.index)
        self.reset()
        self.reset_value_all()
        pose_agv_cur_floor = 1
        pose_agv_dest_floor = 1
        finish = False
        step = 0
        self.state = MainStatePlace.CHECK_ELEVATOR_POSIBLE
        self.pre_state = None
        self.state_when_pause = None
        t1 = datetime.now()
        begin_time_source = datetime.now()
        on_bit = True
        turn_off_when_carry_in_finish = False
        turn_off_when_carry_out_finish = False
        error = None
        if cur_floor == target_floor:
            error = "It is not possible to choose Current Floor with a value equal to Target Floor"
            finish = True
            self.completed.emit(finish)
            ori_time.sleep(0.1)
            self.stop()
        self.log.emit("Mission started")
        while(True):
            self.read_value_x()
            self.read_value_y()
            self.read_value_w_input()
            self.read_value_w_output()
            if self.pre_state != self.state:
                print("{} -------> {}".format(self.pre_state, self.state))
                self.pre_state = self.state
            self.signal.emit(pose_agv_cur_floor)
            self.signal_dest.emit(pose_agv_dest_floor)
            self.completed.emit(finish)
            self.status.emit(step)
            if not connected_plc:
                self.log.emit("Plc disconnected")
                self.stop()
            if (datetime.now() - t1).seconds >= 1:
                if on_bit:
                    write_m(1000,[1])
                    t1 = datetime.now()
                    on_bit = False
                else:
                    write_m(1000,[0])
                    t1 = datetime.now()
                    on_bit = True
            write_m(1001,[1])

            # CARRY_IN
            if self.state == MainStatePlace.CHECK_ELEVATOR_POSIBLE:
                pose_agv_cur_floor = 1
                if read_m(carry_in_instruction_possible[cur_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_cur_floor = 2
                        self.state = MainStatePlace.REQUEST_ENTER_ELEVATOR
                        step = 1
                        begin_time_source = datetime.now()
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePlace.REQUEST_ENTER_ELEVATOR:
                pose_agv_cur_floor = 2
                # write_w(destination_ST_indication[cur_floor-1], [id_floor_destination[target_floor-1]])
                # write_w(carry_in_ID[cur_floor-1], [1])
                # write_m(carry_in_request[cur_floor-1], [1])
                # write_m(request_door_open[cur_floor-1], [1])
                if read_w(destination_ST_indication[cur_floor-1],1)[0] == id_floor_destination[target_floor-1]:
                    step = 2
                if read_w(carry_in_ID[cur_floor-1],1)[0] == 1:
                    step = 3
                if read_m(carry_in_request[cur_floor-1],1)[0] == 1:
                    step = 4
                if read_m(request_door_open[cur_floor-1],1)[0] == 1:
                    step = 0
                if read_m(carry_in_possible[cur_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_cur_floor = 3
                        begin_time_source = datetime.now()
                        self.state = MainStatePlace.CHECK_AGV_PLACE_COMPLETE
                        step = 5
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePlace.CHECK_AGV_PLACE_COMPLETE:
                # write_m(carry_in_completed[cur_floor-1], [1])
                if read_m(carry_in_completed[cur_floor-1],1)[0] == 1:
                    step = 0
                    pose_agv_cur_floor = 2
                if read_w(15,1)[0] == 1 and read_m(2004,1)[0]:
                    self.state = MainStatePlace.DONE_CARRY_IN
                    turn_off_when_carry_in_finish = True
                    begin_time_source = datetime.now()
                    agv_source_move_waiting = True
                    t = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePlace.DONE_CARRY_IN:
                if (datetime.now() - t).seconds >= 5:
                    pose_agv_cur_floor = 1
                    self.state = MainStatePick.CHECK_ELEVATOR_POSIBLE
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE

            # CARRY_IN
            elif self.state == MainStatePick.CHECK_ELEVATOR_POSIBLE:
                pose_agv_dest_floor = 1
                if read_w(carry_out_ID[target_floor-1],1)[0] == 1 and read_m(loading_and_unloading[target_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_dest_floor = 2
                        self.state = MainStatePick.REQUEST_ENTER_ELEVATOR
                        begin_time_source = datetime.now()
                        step = 6
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE

            elif self.state == MainStatePick.REQUEST_ENTER_ELEVATOR:
                # write_m(carry_out_request[target_floor-1], [1])
                if read_m(carry_out_request[target_floor-1],1)[0] == 1:
                    step = 0
                if read_m(carrying_out_possible[target_floor-1],1)[0]:
                    if (datetime.now() - begin_time_source).seconds >= 3:
                        pose_agv_dest_floor = 3
                        self.state = MainStatePick.CHECK_AGV_PICK_COMPLETE
                        begin_time_source = datetime.now()
                        step = 7
                else:
                    begin_time_source = datetime.now()
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE

            elif self.state == MainStatePick.CHECK_AGV_PICK_COMPLETE:
                # write_m(carry_out_completion[target_floor-1], [1])
                if read_m(carry_out_completion[target_floor-1],1)[0] == 1:
                    step = 0
                    pose_agv_dest_floor = 2
                    self.status.emit(step)
                if read_m(completion_ACK[target_floor-1], 1)[0]:
                    agv_dest_move_waiting = True
                    t = datetime.now()
                    self.state = MainStatePick.DONE_CARRY_OUT
                    turn_off_when_carry_out_finish = True
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePick.DONE_CARRY_OUT:
                if (datetime.now() - t).seconds >= 5:
                    pose_agv_dest_floor = 1
                    finish = True
                    self.completed.emit(finish)
                    self.signal_dest.emit(pose_agv_dest_floor)
                    self.log.emit("Mission finished")
                    break
                if pause:
                    self.state_when_pause = self.state
                    self.state = MainStatePlace.PAUSE
            elif self.state == MainStatePlace.PAUSE:
                if read_m(1002,1)[0] == 0:
                    self.log.emit("Agv error")
                    write_m(1002,[1])
                if not pause:
                    self.log.emit("Agv normal")
                    if read_m(1002,1)[0] == 1:
                        write_m(1002,[0])
                    self.state = self.state_when_pause
            if turn_off_when_carry_in_finish:
                 if (datetime.now() - t).seconds >= 1:
                    turn_off_when_carry_in_finish = False
                    write_m(carry_in_completed[cur_floor-1], [0])
                    ori_time.sleep(0.5)
                    write_w(destination_ST_indication[cur_floor-1], [0])
                    write_w(carry_in_ID[cur_floor-1], [0])
                    write_m(carry_in_request[cur_floor-1], [0])
                    write_m(request_door_open[cur_floor-1], [0])
            if turn_off_when_carry_out_finish:
                 if (datetime.now() - t).seconds >= 1:
                    turn_off_when_carry_out_finish = False
                    write_m(carry_out_request[target_floor-1], [0])
                    write_m(carry_out_completion[target_floor-1], [0])

            ori_time.sleep(0.1)
    def stop(self):
        print('Stopping thread...', self.index)
        self.log.emit("Stop mission")
        self.terminate()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1779, 985)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(280, 20, 471, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ip_plc_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ip_plc_text.setInputMask("")
        self.ip_plc_text.setText("")
        self.ip_plc_text.setClearButtonEnabled(False)
        self.ip_plc_text.setObjectName("ip_plc_text")
        self.horizontalLayout.addWidget(self.ip_plc_text)
        self.port_plc_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.port_plc_text.setObjectName("port_plc_text")
        self.horizontalLayout.addWidget(self.port_plc_text)
        self.connect_plc_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connect_plc_button.setObjectName("connect_plc_button")
        self.horizontalLayout.addWidget(self.connect_plc_button)
        self.status_display = QtWidgets.QLabel(self.centralwidget)
        self.status_display.setGeometry(QtCore.QRect(240, 110, 551, 51))
        self.status_display.setObjectName("status_display")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 190, 151, 161))
        self.groupBox.setObjectName("groupBox")
        self.waitting_pose_1 = QtWidgets.QLabel(self.groupBox)
        self.waitting_pose_1.setGeometry(QtCore.QRect(10, 30, 131, 39))
        self.waitting_pose_1.setAlignment(QtCore.Qt.AlignCenter)
        self.waitting_pose_1.setObjectName("waitting_pose_1")
        self.elevator_1 = QtWidgets.QLabel(self.groupBox)
        self.elevator_1.setGeometry(QtCore.QRect(10, 110, 131, 39))
        self.elevator_1.setAlignment(QtCore.Qt.AlignCenter)
        self.elevator_1.setObjectName("elevator_1")
        self.front_elevator_1 = QtWidgets.QLabel(self.groupBox)
        self.front_elevator_1.setGeometry(QtCore.QRect(10, 70, 131, 39))
        self.front_elevator_1.setAlignment(QtCore.Qt.AlignCenter)
        self.front_elevator_1.setObjectName("front_elevator_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 190, 151, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.waitting_pose_2 = QtWidgets.QLabel(self.groupBox_2)
        self.waitting_pose_2.setGeometry(QtCore.QRect(10, 30, 131, 39))
        self.waitting_pose_2.setAlignment(QtCore.Qt.AlignCenter)
        self.waitting_pose_2.setObjectName("waitting_pose_2")
        self.elevator_2 = QtWidgets.QLabel(self.groupBox_2)
        self.elevator_2.setGeometry(QtCore.QRect(10, 110, 131, 39))
        self.elevator_2.setAlignment(QtCore.Qt.AlignCenter)
        self.elevator_2.setObjectName("elevator_2")
        self.front_elevator_2 = QtWidgets.QLabel(self.groupBox_2)
        self.front_elevator_2.setGeometry(QtCore.QRect(10, 70, 131, 39))
        self.front_elevator_2.setAlignment(QtCore.Qt.AlignCenter)
        self.front_elevator_2.setObjectName("front_elevator_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(630, 190, 151, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.waitting_pose_3 = QtWidgets.QLabel(self.groupBox_3)
        self.waitting_pose_3.setGeometry(QtCore.QRect(10, 30, 131, 39))
        self.waitting_pose_3.setAlignment(QtCore.Qt.AlignCenter)
        self.waitting_pose_3.setObjectName("waitting_pose_3")
        self.elevator_3 = QtWidgets.QLabel(self.groupBox_3)
        self.elevator_3.setGeometry(QtCore.QRect(10, 110, 131, 39))
        self.elevator_3.setAlignment(QtCore.Qt.AlignCenter)
        self.elevator_3.setObjectName("elevator_3")
        self.front_elevator_3 = QtWidgets.QLabel(self.groupBox_3)
        self.front_elevator_3.setGeometry(QtCore.QRect(10, 70, 131, 39))
        self.front_elevator_3.setAlignment(QtCore.Qt.AlignCenter)
        self.front_elevator_3.setObjectName("front_elevator_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 390, 811, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 191, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.target_floor_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.target_floor_label.setObjectName("target_floor_label")
        self.horizontalLayout_3.addWidget(self.target_floor_label)
        self.select_target_floor_auto = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.select_target_floor_auto.setObjectName("select_target_floor_auto")
        self.horizontalLayout_3.addWidget(self.select_target_floor_auto)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(230, 40, 191, 78))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cur_floor_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.cur_floor_label.setObjectName("cur_floor_label")
        self.horizontalLayout_2.addWidget(self.cur_floor_label)
        self.select_cur_floor_auto = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.select_cur_floor_auto.setObjectName("select_cur_floor_auto")
        self.horizontalLayout_2.addWidget(self.select_cur_floor_auto)
        self.start_button_auto = QtWidgets.QPushButton(self.groupBox_5)
        self.start_button_auto.setGeometry(QtCore.QRect(440, 40, 81, 81))
        self.start_button_auto.setObjectName("start_button_auto")
        self.stop_button_auto = QtWidgets.QPushButton(self.groupBox_5)
        self.stop_button_auto.setGeometry(QtCore.QRect(550, 40, 81, 81))
        self.stop_button_auto.setObjectName("stop_button_auto")
        self.pause_button_auto = QtWidgets.QPushButton(self.groupBox_5)
        self.pause_button_auto.setGeometry(QtCore.QRect(660, 40, 141, 81))
        self.pause_button_auto.setObjectName("pause_button_auto")
        self.label_status_auto = QtWidgets.QLabel(self.groupBox_5)
        self.label_status_auto.setGeometry(QtCore.QRect(40, 150, 741, 20))
        self.label_status_auto.setText("")
        self.label_status_auto.setObjectName("label_status_auto")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(180, 640, 811, 271))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 191, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.target_floor_label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.target_floor_label_2.setObjectName("target_floor_label_2")
        self.horizontalLayout_4.addWidget(self.target_floor_label_2)
        self.select_target_floor_manual = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.select_target_floor_manual.setObjectName("select_target_floor_manual")
        self.horizontalLayout_4.addWidget(self.select_target_floor_manual)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(230, 40, 191, 78))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cur_floor_label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.cur_floor_label_2.setObjectName("cur_floor_label_2")
        self.horizontalLayout_5.addWidget(self.cur_floor_label_2)
        self.select_cur_floor_manual = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.select_cur_floor_manual.setObjectName("select_cur_floor_manual")
        self.horizontalLayout_5.addWidget(self.select_cur_floor_manual)
        self.start_button_manual = QtWidgets.QPushButton(self.groupBox_6)
        self.start_button_manual.setGeometry(QtCore.QRect(440, 40, 81, 81))
        self.start_button_manual.setObjectName("start_button_manual")
        self.set_bit_button = QtWidgets.QPushButton(self.groupBox_6)
        self.set_bit_button.setGeometry(QtCore.QRect(660, 130, 141, 81))
        self.set_bit_button.setObjectName("set_bit_button")
        self.select_bit = QtWidgets.QComboBox(self.groupBox_6)
        self.select_bit.setGeometry(QtCore.QRect(10, 154, 621, 41))
        self.select_bit.setObjectName("select_bit")
        self.stop_button_manual = QtWidgets.QPushButton(self.groupBox_6)
        self.stop_button_manual.setGeometry(QtCore.QRect(550, 40, 81, 81))
        self.stop_button_manual.setObjectName("stop_button_manual")
        self.pause_button_manual = QtWidgets.QPushButton(self.groupBox_6)
        self.pause_button_manual.setGeometry(QtCore.QRect(660, 40, 141, 81))
        self.pause_button_manual.setObjectName("pause_button_manual")
        self.label_status_manual = QtWidgets.QLabel(self.groupBox_6)
        self.label_status_manual.setGeometry(QtCore.QRect(30, 230, 751, 20))
        self.label_status_manual.setText("")
        self.label_status_manual.setObjectName("label_status_manual")
        self.radioButton_auto = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_auto.setGeometry(QtCore.QRect(40, 460, 112, 23))
        self.radioButton_auto.setObjectName("radioButton_auto")
        self.radioButton_manual = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_manual.setGeometry(QtCore.QRect(40, 760, 112, 23))
        self.radioButton_manual.setObjectName("radioButton_manual")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(1150, 620, 581, 291))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1420, 590, 67, 17))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1779, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # """
        # .########.########..####.########
        # .##.......##.....##..##.....##...
        # .##.......##.....##..##.....##...
        # .######...##.....##..##.....##...
        # .##.......##.....##..##.....##...
        # .##.......##.....##..##.....##...
        # .########.########..####....##...
        # """
        # init variable
        self.init_variable()
        # init function
        self.init_function(MainWindow)
        # set property
        self.set_property()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ip_plc_text.setPlaceholderText(_translate("MainWindow", "Insert plc address"))
        self.port_plc_text.setPlaceholderText(_translate("MainWindow", "Insert plc port"))
        self.connect_plc_button.setText(_translate("MainWindow", "Connect Plc"))
        self.status_display.setText(_translate("MainWindow", "Disconnected"))
        self.groupBox.setTitle(_translate("MainWindow", "Agv floor 1 position"))
        self.waitting_pose_1.setText(_translate("MainWindow", "waitting pose"))
        self.elevator_1.setText(_translate("MainWindow", "elevator "))
        self.front_elevator_1.setText(_translate("MainWindow", "front elevator"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Agv floor 2 position"))
        self.waitting_pose_2.setText(_translate("MainWindow", "waitting pose"))
        self.elevator_2.setText(_translate("MainWindow", "elevator "))
        self.front_elevator_2.setText(_translate("MainWindow", "front elevator"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Agv floor 3 position"))
        self.waitting_pose_3.setText(_translate("MainWindow", "waitting pose"))
        self.elevator_3.setText(_translate("MainWindow", "elevator "))
        self.front_elevator_3.setText(_translate("MainWindow", "front elevator"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Input auto"))
        self.target_floor_label.setText(_translate("MainWindow", "Target Floor:"))
        self.cur_floor_label.setText(_translate("MainWindow", "Current Floor:"))
        self.start_button_auto.setText(_translate("MainWindow", "Start "))
        self.stop_button_auto.setText(_translate("MainWindow", "Stop"))
        self.pause_button_auto.setText(_translate("MainWindow", "Agv error"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Input manual"))
        self.target_floor_label_2.setText(_translate("MainWindow", "Target Floor:"))
        self.cur_floor_label_2.setText(_translate("MainWindow", "Current Floor:"))
        self.start_button_manual.setText(_translate("MainWindow", "Start"))
        self.set_bit_button.setText(_translate("MainWindow", "Set value address"))
        self.stop_button_manual.setText(_translate("MainWindow", "Stop"))
        self.pause_button_manual.setText(_translate("MainWindow", "Agv error"))
        self.radioButton_auto.setText(_translate("MainWindow", "Auto Mode"))
        self.radioButton_manual.setText(_translate("MainWindow", "Manual Mode"))
        self.label.setText(_translate("MainWindow", "Logs"))


    def init_variable(self):
        self.cur_floor = 1
        self.target_floor = 1
        self.plc_address = None
        self.port = None
        self.connected = False
        self.groupBox_5.setEnabled(False)
        self.groupBox_6.setEnabled(False)
        self.radioButton_auto.setCheckable(True)
        self.radioButton_manual.setCheckable(True)
        self.radioButton_auto.setEnabled(False)
        self.radioButton_manual.setEnabled(False)
        self.stop_button_auto.setEnabled(False)
        self.start_button_auto.setEnabled(True)
        self.stop_button_manual.setEnabled(False)
        self.start_button_manual.setEnabled(True)
        self.clear_text = False
        self.plainTextEdit.setReadOnly(True)
    def set_property(self):
        self.set_color_status_elevator()
        self.select_target_floor_auto.addItem("1")
        self.select_target_floor_auto.addItem("2")
        self.select_target_floor_auto.addItem("3")
        self.select_target_floor_manual.addItem("1")
        self.select_target_floor_manual.addItem("2")
        self.select_target_floor_manual.addItem("3")
        self.select_cur_floor_auto.addItem("1")
        self.select_cur_floor_auto.addItem("2")
        self.select_cur_floor_auto.addItem("3")
        self.select_cur_floor_manual.addItem("1")
        self.select_cur_floor_manual.addItem("2")
        self.select_cur_floor_manual.addItem("3")
        self.radioButton_auto.toggled.connect(lambda:self.btnstate(self.radioButton_auto))
        self.radioButton_manual.toggled.connect(lambda:self.btnstate(self.radioButton_manual))
        self.status_display.setAlignment(QtCore.Qt.AlignCenter)
        self.status_display.setStyleSheet("background-color: \
                            rgba(255,255,0,255); ")
        self.label_status_auto.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_manual.setAlignment(QtCore.Qt.AlignCenter)
    def btnstate(self, b):
        if b.text() == "Auto Mode":
            self.label_status_manual.setText("")
            if b.isChecked() == True:
                print (b.text()+" is selected")
                self.groupBox_5.setEnabled(True)
                self.pause_button_auto.setEnabled(False)
                self.label_status_auto.setText("Wait new mission")
            else:
                self.label_status_auto.setText("")
                self.groupBox_5.setEnabled(False)
                print (b.text()+" is deselected")
        if b.text() == "Manual Mode":
            self.label_status_auto.setText("")
            if b.isChecked() == True:
                self.groupBox_6.setEnabled(True)
                print (b.text()+" is selected")
                self.pause_button_manual.setEnabled(False)
                self.label_status_manual.setText("Wait new mission")
            else:
                self.label_status_manual.setText("")
                self.groupBox_6.setEnabled(False)
                print (b.text()+" is deselected")
    def set_color_agv_1(self,number = 1):
        if number == 1:
            self.waitting_pose_1.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.waitting_pose_1.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        if number == 2:
            self.front_elevator_1.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.front_elevator_1.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        if number == 3:
            self.elevator_1.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.elevator_1.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
    def set_color_agv_2(self,number = 1):
        if number == 1:
            self.waitting_pose_2.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.waitting_pose_2.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        if number == 2:
            self.front_elevator_2.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.front_elevator_2.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        if number == 3:
            self.elevator_2.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.elevator_2.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
    def set_color_agv_3(self,number = 1):
        if number == 1:
            self.waitting_pose_3.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.waitting_pose_3.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        if number == 2:
            self.front_elevator_3.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.front_elevator_3.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        if number == 3:
            self.elevator_3.setStyleSheet("background-color: \
                           rgba(255,255,0,255); ")
        else:
            self.elevator_3.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
    def set_color_status_elevator(self):
        self.elevator_1.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.elevator_2.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.elevator_3.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.waitting_pose_1.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.waitting_pose_2.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.waitting_pose_3.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.elevator_1.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.elevator_2.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.elevator_3.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
        self.status_display.setStyleSheet("background-color: \
                           rgba(255,255,0,0); ")
    def init_function(self,MainWindow):
        self.connect_plc_button.clicked.connect(self.clickPlc)
        # self.start_button_auto.clicked.connect(self.clickStartAuto)
        # self.start_button_manual.clicked.connect(self.clickStartManual)
        ipRange = "(?:[0-1]?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])"
        ipRegex = QtCore.QRegExp("^" + ipRange + "\\." + ipRange + "\\." + ipRange + "\\." + ipRange + "$")
        ipValidator = QtGui.QRegExpValidator(ipRegex, MainWindow)
        self.ip_plc_text.setValidator(ipValidator)
        self.port_plc_text.setValidator(QtGui.QIntValidator(1,99999999))

        self.thread = {}

        self.start_button_auto.clicked.connect(self.start_auto)
        self.start_button_manual.clicked.connect(self.start_manual)

        self.stop_button_auto.clicked.connect(self.stop_auto)
        self.stop_button_manual.clicked.connect(self.stop_manual)

        self.set_bit_button.clicked.connect(self.click_set_bit)

        self.pause_button_auto.clicked.connect(self.pause_resume)
        self.pause_button_manual.clicked.connect(self.pause_resume)
    def clear_param(self):
        pass

    # """
    # .########.##.....##.##....##..######..########.####..#######..##....##
    # .##.......##.....##.###...##.##....##....##.....##..##.....##.###...##
    # .##.......##.....##.####..##.##..........##.....##..##.....##.####..##
    # .######...##.....##.##.##.##.##..........##.....##..##.....##.##.##.##
    # .##.......##.....##.##..####.##..........##.....##..##.....##.##..####
    # .##.......##.....##.##...###.##....##....##.....##..##.....##.##...###
    # .##........#######..##....##..######.....##....####..#######..##....##
    # """

    def start_auto(self):
        self.plainTextEdit.clear()
        ori_time.sleep(0.5)
        global cur_floor, target_floor, stop
        stop = False
        self.cur_floor = self.select_target_floor_auto.currentText()
        self.target_floor = self.select_cur_floor_auto.currentText()
        cur_floor = int(self.cur_floor)
        target_floor = int(self.target_floor)
        print("cur_floor: {}".format(self.cur_floor))
        print("target_floor: {}".format(self.target_floor))
        self.thread[1] = ThreadAuto(index=1)
        self.thread[1].start()
        self.thread[1].signal.connect(self.agv_source)
        self.thread[1].signal_dest.connect(self.agv_dest)
        self.thread[1].completed.connect(self.reset_finish)
        self.thread[1].log.connect(self.logs)
        self.start_button_auto.setEnabled(False)
        self.set_color_agv_1(0)
        self.set_color_agv_2(0)
        self.set_color_agv_3(0)
        self.pause_button_auto.setEnabled(True)
        self.pause_button_auto.setText("Agv error")
        self.label_status_auto.setText("Mission is running")
        self.stop_button_auto.setEnabled(True)
        self.radioButton_manual.setEnabled(False)
    def start_manual(self):
        self.plainTextEdit.clear()
        ori_time.sleep(0.5)
        global cur_floor, target_floor, stop
        stop = False
        self.cur_floor = self.select_target_floor_manual.currentText()
        self.target_floor = self.select_cur_floor_manual.currentText()
        cur_floor = int(self.cur_floor)
        target_floor = int(self.target_floor)
        print("cur_floor: {}".format(self.cur_floor))
        print("target_floor: {}".format(self.target_floor))
        self.thread[2] = ThreadManual(index=2)
        self.thread[2].start()
        self.thread[2].signal.connect(self.agv_source)
        self.thread[2].signal_dest.connect(self.agv_dest)
        self.thread[2].completed.connect(self.reset_finish)
        self.thread[2].status.connect(self.set_combobox_manual)
        self.thread[2].log.connect(self.logs)
        self.start_button_manual.setEnabled(False)
        self.set_color_agv_1(0)
        self.set_color_agv_2(0)
        self.set_color_agv_3(0)
        self.pause_button_manual.setEnabled(True)
        self.pause_button_manual.setText("Agv error")
        self.label_status_manual.setText("Mission is running")
        self.stop_button_manual.setEnabled(True)
        self.radioButton_auto.setEnabled(False)
    def stop_auto(self):
        global stop
        stop = True
        ori_time.sleep(0.5)
        self.thread[1].stop()
        # self.uic.lcdNumber_1.display(0)
        self.stop_button_auto.setEnabled(False)
        self.set_color_agv_1(0)
        self.set_color_agv_2(0)
        self.set_color_agv_3(0)
        self.pause_button_auto.setEnabled(False)
        self.label_status_auto.setText("Mission is stopped")
        self.start_button_auto.setEnabled(True)
        self.radioButton_manual.setEnabled(True)
    def stop_manual(self):
        global stop
        stop = True
        ori_time.sleep(0.5)
        self.thread[2].stop()
        # self.uic.lcdNumber_2.display(0)
        self.stop_button_manual.setEnabled(False)
        self.set_color_agv_1(0)
        self.set_color_agv_2(0)
        self.set_color_agv_3(0)
        self.pause_button_manual.setEnabled(False)
        self.label_status_manual.setText("Mission is stopped")
        self.start_button_manual.setEnabled(True)
        self.radioButton_auto.setEnabled(True)
    def reset_finish(self, counter):
        if counter:
            self.radioButton_manual.setEnabled(True)
            self.radioButton_auto.setEnabled(True)
            self.stop_button_auto.setEnabled(False)
            self.start_button_auto.setEnabled(True)
            self.stop_button_manual.setEnabled(False)
            self.start_button_manual.setEnabled(True)
            if error is None:
                self.label_status_manual.setText("Mission is finished")
                self.label_status_auto.setText("Mission is finished")
            else:
                self.label_status_auto.setText(error)
                self.label_status_manual.setText(error)
            self.pause_button_auto.setEnabled(False)
            self.pause_button_manual.setEnabled(False)

    def click_set_bit(self):
        if cur_counter == 1:
            write_w(destination_ST_indication[cur_floor-1], [id_floor_destination[target_floor-1]])
        elif cur_counter == 2:
            write_w(carry_in_ID[cur_floor-1], [1])
        elif cur_counter == 3:
            write_m(carry_in_request[cur_floor-1], [1])
        elif cur_counter == 4:
            write_m(request_door_open[cur_floor-1], [1])
        elif cur_counter == 5:
            write_m(carry_in_completed[cur_floor-1], [1])
        elif cur_counter == 6:
            write_m(carry_out_request[target_floor-1], [1])
        elif cur_counter == 7:
            write_m(carry_out_completion[target_floor-1], [1])
    def set_combobox_manual(self, counter):
        global pre_counter, cur_counter
        cur_counter = counter
        # print("set_text_combobox :{}".format(counter))
        if counter == 0 or counter != pre_counter:
            pre_counter = counter
            self.select_bit.clear()
            self.clear_text = True
            # self.set_bit_button.setEnabled(False)
        elif counter == 1:
            if self.clear_text:
                self.clear_text = False
                if cur_floor == 1:
                    self.select_bit.addItem("1 frontage destination ST indication (W100-101)")
                elif cur_floor == 2:
                    self.select_bit.addItem("2 frontage destination ST indication (W102-103)")
                elif cur_floor == 3:
                    self.select_bit.addItem("3 frontage destination ST indication (W104-105)")
        elif counter == 2:
            if self.clear_text:
                self.clear_text = False
                if cur_floor == 1:
                    self.select_bit.addItem("1 frontage carry-in ID (W120)")
                elif cur_floor == 2:
                    self.select_bit.addItem("2 frontage carry-in ID (W121)")
                elif cur_floor == 3:
                    self.select_bit.addItem("3 frontage carry-in ID (W122)")
        elif counter == 3:
            if self.clear_text:
                self.clear_text = False
                if cur_floor == 1:
                    self.select_bit.addItem("1 frontage carry-in request (M1030)")
                elif cur_floor == 2:
                    self.select_bit.addItem("2 frontage carry-in request (M1031)")
                elif cur_floor == 3:
                    self.select_bit.addItem("3 frontage carry-in request (M1032)")
        elif counter == 4:
            if self.clear_text:
                self.clear_text = False
                if cur_floor == 1:
                    self.select_bit.addItem("1 request_door_open (M1090)")
                elif cur_floor == 2:
                    self.select_bit.addItem("2 request_door_open (M1091)")
                elif cur_floor == 3:
                    self.select_bit.addItem("3 request_door_open (M1092)")
        elif counter == 5:
            if self.clear_text:
                self.clear_text = False
                if cur_floor == 1:
                    self.select_bit.addItem("1 Frontage carry-in completed (M1040)")
                elif cur_floor == 2:
                    self.select_bit.addItem("2 Frontage carry-in completed (M1041)")
                elif cur_floor == 3:
                    self.select_bit.addItem("3 Frontage carry-in completed (M1042)")
        elif counter == 6:
            if self.clear_text:
                self.clear_text = False
                if target_floor == 1:
                    self.select_bit.addItem("1 frontage carry-out request (M1050)")
                elif target_floor == 2:
                    self.select_bit.addItem("2 frontage carry-out request (M1051)")
                elif target_floor == 3:
                    self.select_bit.addItem("3 frontage carry-out request (M1052)")
        elif counter == 7:
            if self.clear_text:
                self.clear_text = False
                if target_floor == 1:
                    self.select_bit.addItem("1 frontage carry-out completion (M1060)")
                elif target_floor == 2:
                    self.select_bit.addItem("2 frontage carry-out completion (M1061)")
                elif target_floor == 3:
                    self.select_bit.addItem("3 frontage carry-out completion (M1062)")

    def agv_dest(self, counter):
        if target_floor == 1:
            self.set_color_agv_1(counter)
        elif target_floor == 2:
            self.set_color_agv_2(counter)
        elif target_floor == 3:
            self.set_color_agv_3(counter)
    def agv_source(self, counter):
        # m = counter
        # if m == 1:
        #     self.uic.lcdNumber_1.display(1)
        # elif m == 3:
        #     self.uic.lcdNumber_1.display(2)
        # elif m == 6:
        #     self.uic.lcdNumber_1.display(3)
        # elif m == 10:
        #     self.uic.lcdNumber_1.display(4)
        # print("counter: {}".format(counter))
        if cur_floor == 1:
            self.set_color_agv_1(counter)
        elif cur_floor == 2:
            self.set_color_agv_2(counter)
        elif cur_floor == 3:
            self.set_color_agv_3(counter)
    def clickPlc(self):
        global connected_plc, plc
        self.set_color_status_elevator()
        if not self.connected:
            self.plc_address = self.ip_plc_text.text()
            self.port = self.port_plc_text.text()
            try:
                if not check_plc_connected():
                    plc_connect(str(self.plc_address), int(self.port))
                # self.set_color_status_elevator()
                self.status_display.setStyleSheet("background-color: \
                            rgba(255,255,0,255); ")
                self.status_display.setText("Connected")
                self.connected = True
                self.radioButton_auto.setEnabled(True)
                self.radioButton_manual.setEnabled(True)
                self.connect_plc_button.setText("Disconnect Plc")
            except Exception as e:
                self.connected = False
                self.radioButton_auto.setEnabled(False)
                self.radioButton_manual.setEnabled(False)
                self.error = e
                print(e)
                self.get_error(self.error)
        else:
            self.connect_plc_button.setText("Connect Plc")
            self.status_display.setStyleSheet("background-color: \
                            rgba(255,255,0,255); ")
            self.status_display.setText("Disconnected")
            self.radioButton_auto.setCheckable(False)
            self.radioButton_manual.setCheckable(False)
            self.init_variable()
        connected_plc = self.connected
    def get_error(self, text):
        self.status_display.setStyleSheet("background-color: \
                           rgba(255,0,0,255); ")
        if len(self.plc_address) == 0:
            self.error = "Please insert plc address"
        elif len(self.port) == 0:
            self.error = "Please insert plc port"
        self.status_display.setText("Error: {}".format(self.error))
        # self.status_display.adjustSize()
    def clickStartAuto(self):
        self.cur_floor = self.select_target_floor_auto.currentText()
        self.target_floor = self.select_cur_floor_auto.currentText()
        self.state = MainStatePlace.CHECK_ELEVATOR_POSIBLE
        while(True):
            write_m(1000,[1])
            write_m(1001,[1])
            print(self.state)
            if self.state == MainStatePlace.CHECK_ELEVATOR_POSIBLE:
                if read_m(1021,1)[0]:
                    self.set_color_agv_1(1)
                    self.state = MainStatePlace.REQUEST_ENTER_ELEVATOR

            elif self.state == MainStatePlace.REQUEST_ENTER_ELEVATOR:
                write_w(102, [1003])
                write_w(121, [1])
                write_m(1031, [1])
                if read_m(1051,1)[0]:
                    self.state = MainStatePlace.CHECK_AGV_PLACE_COMPLETE

            elif self.state == MainStatePlace.CHECK_AGV_PLACE_COMPLETE:
                write_m(1041, [1])
                if read_w(15,1)[0] == 1 and read_m(1004,1)[0]:
                    self.state = MainStatePick.CHECK_ELEVATOR_POSIBLE

            elif self.state == MainStatePick.CHECK_ELEVATOR_POSIBLE:
                if read_w(32,1)[0] == 1 and read_m(1062,1)[0]:
                    self.state = MainStatePick.REQUEST_ENTER_ELEVATOR

            elif self.state == MainStatePick.REQUEST_ENTER_ELEVATOR:
                write_m(1052, [1])
                if read_m(1072,1)[0]:
                    self.state = MainStatePick.CHECK_AGV_PICK_COMPLETE

            elif self.state == MainStatePick.CHECK_AGV_PICK_COMPLETE:
                write_m(1062, [1])
                if read_m(1082, 1)[0]:
                    break

    def clickStartManual(self):
        self.cur_floor = self.select_target_floor_manual.currentText()
        self.target_floor = self.select_cur_floor_manual.currentText()
        if read_y(1021,1):
            print(read_y(1021,1))
        print(MainStatePick.NONE.value)
    def pause_resume(self):
        global pause
        if  self.radioButton_auto.isChecked():
            if self.pause_button_auto.text() == "Agv error" :
                pause = True
                self.pause_button_auto.setText("Reset error")
            elif self.pause_button_auto.text() == "Reset error" :
                self.pause_button_auto.setText("Agv error")
                pause = False
        elif  self.radioButton_manual.isChecked():
            if self.pause_button_manual.text() == "Agv error" :
                self.pause_button_manual.setText("Reset error")
                pause = True
            elif self.pause_button_manual.text() == "Reset error" :
                self.pause_button_manual.setText("Agv error")
                pause = False

    def logs(self, record):
        # msg = self.format(record)
        time = QTime.currentTime()
        t = time.toString()
        self.plainTextEdit.appendPlainText(t + ":       " + record)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
